python infer.py --model_id "abnet-wmt16-ro-en" \
    --tr_tgt_file "data/wmt16/<something>" \
    --tr_src_file "data/wmt16/<something>" \
    --val_tgt_file "data/wmt16/<something>" \
    --val_src_file "data/wmt16/<something>" \
    --tst_tgt_file "data/wmt16/<something>" \
    --tst_src_file "data/wmt16/<something>" \
    --iterations 10 \
    --k 4 \
    --batch_size 8 \
    --num_workers 4 \
    --max_length 32 \
    --max_target_length 32 \
    --tr_max_samples 2000 \
    --val_max_samples 2000 \
    --tst_max_samples 2000
